# Generated by Django 5.0.1 on 2024-02-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador1_id', models.IntegerField(default=-1)),
                ('jugador2_id', models.IntegerField(default=-1)),
                ('empezado', models.BooleanField(default=False)),
                ('terminado', models.BooleanField(default=False)),
                ('comienzo', models.DateTimeField()),
                ('jugador1_marcador', models.IntegerField(default=0)),
                ('jugador2_marcador', models.IntegerField(default=0)),
                ('pausa', models.BooleanField(verbose_name=False)),
                ('finDePausa', models.DateTimeField()),
                ('pelota_actualizacion', models.DateTimeField()),
                ('pelota_x', models.FloatField(default=0)),
                ('pelota_y', models.FloatField(default=0)),
                ('pelota_velocidad_x', models.FloatField(default=0)),
                ('pelota_velocidad_y', models.FloatField(default=0)),
                ('jugador1_actualizacion', models.DateTimeField()),
                ('jugador1_y', models.FloatField(default=0)),
                ('jugador1_velocidad_y', models.FloatField(default=0)),
                ('jugador2_actualizacion', models.DateTimeField()),
                ('jugador2_y', models.FloatField(default=0)),
                ('jugador2_velocidad_y', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('J', 'Jugador'), ('A', 'Administrador')], max_length=1)),
            ],
        ),
    ]
