# Generated by Django 5.0.1 on 2024-02-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='comienzo',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='finDePausa',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='jugador1_actualizacion',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='jugador2_actualizacion',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='pelota_actualizacion',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
