# Generated by Django 5.0.1 on 2024-02-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_partido_comienzo_alter_partido_findepausa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='pausa',
            field=models.BooleanField(default=False),
        ),
    ]
