# Generated by Django 5.0.1 on 2024-02-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_partido_desconectado_partido_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='comienzo',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='finDePausa',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='jugador1_actualizacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='jugador2_actualizacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='pelota_actualizacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
