# Generated by Django 3.0.7 on 2024-02-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_usuario_remove_partido_jugador1_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
